version: "3"

services:

     software-shinobi-share:
          container_name: software-shinobi-share
          image: nextcloud:latest
          restart: "always"
          ports:
               - 12221:80
          volumes:
               - ./volume-data/nextcloud-content:/var/www/html
