version: '3'

services:

  odoo-database:
    container_name: odoo-database
    image: postgres:10
    restart: always
    volumes:
      - odoo-database-data:/var/lib/postgresql/data/pgdata
    ports:
      - 18432:5432/tcp
    environment:
    - PGDATA=/var/lib/postgresql/data/pgdata
    - POSTGRES_DB=postgres
    - POSTGRES_USER=odoo
    - POSTGRES_PASSWORD=odoo 

  odoo-server:
    container_name: odoo-server
    depends_on:
      - odoo-database
    image: odoo:12.0
    restart: always
    ports:
      - "18080:8069/tcp"
    links:
      - odoo-database:db
    volumes:
      - odoo-server-data:/var/lib/odoo

volumes:
  odoo-database-data:
    external: true
  odoo-server-data:
    external: true